### ISSUE TITLE
As a user, I want a clean UI

### ISSUE THREAD

**Issue by Aboisier** [red-kite-solutions/stalker#162]
AC:

- [x] UI dependencies updated
- [x] Flex layout removed
- [x] All pages have a similar layout
- [x] Search bar is hidden
- [x] Dashboard improved
- [x] Dark + light theme synced with system or overridable
- [x] Question mark documentation is the wrong color
- [x] Code editor theme is synced with the theme
- [x] In job pages, the code takes the whole page

**Comment by lm-sec** [comment]
#186 could be useful

**Comment by lm-sec** [comment]
- [ ] Image selection text is broken in edit project
![image](https://github.com/red-kite-solutions/stalker/assets/21041333/349f0dc6-c941-4982-bc6b-dc80c26a8c34)
