### ISSUE TITLE
As a french speaking user, I want to switch languages

### ISSUE THREAD

**Issue by Aboisier** [red-kite-solutions/stalker#186]
So that I can understand the UI.

**Comment by lm-sec** [comment]
@k44sh this might be a good issue for you if you are looking for something to do over a weekend. 

It will probably require to add an nginx to the infrastructure that properly serves the `/en/` and `/fr/` requests. You could even detect the browser language! :eyes: I would leave the implementation details to the implementer, but it is an infrastructure issue, so I thought you might be interested.

It also includes adding a button to the UI, but I would gladly add it for you if that is an issue.

It also includes modifying the architecture doc, but I could take care of that as well.
