### ISSUE TITLE
As a user, I want to see my resources as a graph.

### ISSUE THREAD

**Issue by lm-sec** [red-kite-solutions/stalker#303]
**AC:**

Graph with links between resources.

**Nodes (minimum):**

Domain
Host
Port
Website
(Project?)

**Library:**

https://visjs.github.io/vis-network/examples/network/labels/labelAlignment.html
https://visjs.github.io/vis-network/docs/network/nodes.html

**Comment by Aboisier** [comment]
Promoted to Red Kite Enterprise.
